---
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: insightful-routines:latest
    working_dir: "/app"
    volumes:
      - "${PWD}/data/:/app/data/"
      - "${PWD}/.env:/app/.env:ro"
    restart: unless-stopped
    command: insightful-routines-bot
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=USER # change to username
      - POSTGRES_PASSWORD=PASSWORD # change to password
      - POSTGRES_DB=DB_NAME # change to database name
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  